### ISSUE TITLE
Rename The Gem?

### ISSUE THREAD

**Issue by benhamill** [texticle/texticle#11]
Several times recently, I've seen people mentioned texticle in lists of gems with immature or potentially offensive (or oppressive) names ([one example](http://iampedantic.com/post/25437120283/project-names-in-poor-taste)). Honestly, I've never thought the name was super funny and there's something to be said for not needlessly sexualizing the programming environment, so I'm pretty inclined to rename it. If @ecin and I can agree on a new name, that would be ideal, to me. Does anyone have any cool suggestions?

**Comment by benhamill** [comment]
Thinking of fun things:
- [dradis](http://en.battlestarwiki.org/wiki/DRADIS)
- [palantir](http://en.wikipedia.org/wiki/Palantir)
- crystal_ball
- [gently](http://en.wikipedia.org/wiki/Dirk_Gently)
- [scry](http://en.wikipedia.org/wiki/Scrying)
- [demonic_tutor](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=202628) (Or [another tutor card](http://gatherer.wizards.com/Pages/Search/Default.aspx?name=+[tutor]), maybe)

On the less-fun side:
- pg-search

**Comment by benhamill** [comment]
Maybe `gorby_puff` as a nod to the original author, @tenderlove.

**Comment by ecin** [comment]
Wow, can't believe scry isn't taken. pg_search is though, so pg-search would just cause unnecessary confusion. All for gorby_puff if @tenderlove would accept this gem as its namesake.

"searchable" is also available, and we already use this name as a module in the gem.

**Comment by benhamill** [comment]
The chances that Aaron will see a notification about this thread are low. Do you think it's worth pinging him on Twitter about it? Or maybe the @gorby_puff account.

Alternatively, maybe that's too obtuse. I feel like scry is my favorite so far, but I'm not really loving any of them.

**Comment by ecin** [comment]
Naming is hard. Let's go shopping.

**Comment by benhamill** [comment]
Shockingly, shopping is not taken as a gem name. Heh. :wink:

**Comment by benhamill** [comment]
Maybe go for a Harry Potter reference? [Accio](http://en.wikipedia.org/wiki/List_of_spells_in_Harry_Potter) is their summoning spell.

**Comment by tenderlove** [comment]
gorbypuff is fine with me! :-)

**Comment by benhamill** [comment]
Maybe we should take one step aside from that idea. I feel like `gorbachev` would be more-easily-rememberable to people not super familiar with @tenderlove's cat. Thoughts?

**Comment by mmaa** [comment]
pigfits

(PG FTS)

**Comment by benhamill** [comment]
OK. I'm going with `gorbachev` and will make this Issue into a PR later on.

**Comment by benhamill** [comment]
For my own organizational purposes, this means we should:
- Add a deprecation warning to use of the `texticle` name.
- Make the `gorbachev` name available in the `texticle` gem.

After that, we can make a `gorbachev` release and rename repos or whatever we're going to do. Not sure, yet, whether to start the new name with 1.0 or inherit the version number from texticle. Right now, leaning towards keeping the version number (so that gorbachev 3.0.0 will be the first one without deprecation warnings about stuff).

**Comment by sj26** [comment]
I like that "texticle" nods to the gems treatment of text. Personally, I don't mind the name at all, evokes a fondness from me.

My next choice would be the perfunctory "searchable". The use of the namespace is established. It also fits the trend towards adjective naming convention for concerns.

"Gorbachev" might be confusing. "Gorbachov" is actually the more correct romanization of the [statesman's](http://en.wikipedia.org/wiki/Mikhail_Gorbachev) name. It also doesn't seem very relevant to search.

**Comment by benhamill** [comment]
The Wikipedia article you link uses the -ev ending for the name. Admittedly, it has nothing to do with search, only with Aaron's cat. I think, probably, it's a bleh name and, earlier, I was just acting desperate.

I'm not a big fan of super-descriptive gem names, personally. A pun is fine or whatever, but consider `sidekiq`, `devise`, `kaminari` or `capybara`. I'm not against entertaining more suggestions, if you have an idea that's both more relevant and more fun that `gorbachev`.

What I _am_ against is a name that needlessly sexualizes conversation about code. I don't feel like it's funny enough to make up for that fact. We can do better than "hee hee balls", I'm sure.

Here's some random 'text-' puns I came up with:
- `texture`
- `textend` (Since this is an extension of Postgres?)
- `textension` (above, but longer)
- `textant` (I like the play on sextant, but there's a gem [named that](https://rubygems.org/gems/sextant) already)
- `textort`
- `textra` (This is a play on extra, but also just kinda sounds cool, or is a powerful text-related spell in Final Fantasy, maybe)
- `textract`
- `textreme`
- `textrinsic`
- `textable` (meh)

Of those, I think I like `textant` and `textra` the best.

**Comment by h3h** [comment]
- `searchgres`
- `seekgres`
- `textgres`
- `textgress`
- `francisdrake`
- `eldraque`
- `cortes`

**Comment by ascruggs** [comment]
textacular

**Comment by benhamill** [comment]
On Sat, Jan 12, 2013 at 7:14 PM, @ascruggs wrote:

> textacular

I'm really surprised this isn't already taken. Huh!

Thanks for the further suggestions, folks!

**Comment by sj26** [comment]
"textacular" sounds great. :+1:

**Comment by DBNess** [comment]
textacular is great. thanks for doing this, @benhamill !

**Comment by olivierlacan** [comment]
Yep, I'll vote for **textacular** too. But I'll still snicker like an idiot remembering it was once called texticle.

You should probably grab the org before it's snatched by another project.

**Comment by pvh** [comment]
Hey guys, I think "textacular" is a great name. I sure would love for you to make this change! 

I really love what this gem does, but right now I don't feel comfortable talking about it on stage or in public because of how it might make some of the people in the audience feel.

If there's anything that I can do to help, please let me know.

**Comment by benhamill** [comment]
Yeah. I think Textacular is the winner. I made an [organization](https://github.com/textacular), but I haven't had time to do much else. This is just a matter of allotting free time to it. Thanks, everyone, for your feedback.

**Comment by pvh** [comment]
Hey look over here! https://github.com/texticle/texticle/pull/27

**Comment by benhamill** [comment]
OK, everyone. Here you go: https://github.com/textacular/textacular

**Comment by kokethebest** [comment]
xD... now i get it!
