### ISSUE TITLE
Update documentation to mention trigram indexes

### ISSUE THREAD

**Issue by joevandyk** [texticle/texticle#14]
We should mention in the texticle documentation that using a trigram index in postgresql 9.1+ might save you from having to do full-text search in postgresql.

See https://raw.github.com/gist/4d7ba9e63270b685d570/415494710f401ccfc11365b240e83bb1798578e7/gistfile1.txt for an example.

**Comment by benhamill** [comment]
This seems legit. If you still have this test data around, can you compare also using `fuzzy_search` from the master branch?

**Comment by benhamill** [comment]
Just noticed that your two searches returned a different number of rows? 4 and then 11? What's up with that?

**Comment by joevandyk** [comment]
The rows in the explain output isn't the number of rows returned by the query, but rather the number of rows in the explain output.
