### ISSUE TITLE
Search model and associated model fields

### ISSUE THREAD

**Issue by amnesia7** [texticle/texticle#15]
I was wondering whether Texticle can search the fields of the main model as well as fields in a sub-model, eg title, body from Article model as well as the name field from the associated Tag model (an article has multiple tags).

I read the readme but couldn't see any mention of this on there.

pg_search says that it can do it (https://github.com/Casecommons/pg_search#searching-through-associations) but it doesn't seem to use indexes. If Texticle can do associations does it suffer from the same issue?

Thanks

**Comment by benhamill** [comment]
You should be able to do something like this: `Article.join(:tags).search(tags: { name: search_term })`. Will that do what you're looking for?

**Comment by amnesia7** [comment]
Thanks @benhamill.

Do you know if there is any reason why this would not use the database indexes? I'm not sure why pg_search doesn't.

I haven't put my `Tag` model in place yet so I've not much to test against yet. Do you know if it is normal to use a separate model for tags or whether the convention is to add a `tags` field to the `Article` model and put them in there comma-separated?
This would make AR queries and searching more straight-forward (since it would be in the same model) but I wonder if I wanted to use tags for autocomplete (for example) then I would need to add any new unique tags to a separate tags model.

Thanks

**Comment by benhamill** [comment]
I don't know about pg_search at all, so I'm not sure how it builds indexes. As far as I know, texticle should use indexes unless Postgres decides it'll be slower. Sometimes, it's faster to use a different index to bust down the result set and then do the full text search, but that depends on what else is going on in the query.

As for what's "normal" for tagging things, I can't say. People tag things for different reasons in different ways. In a vacuum, I'd say use a related model with a many-to-many relationship. I'm pretty sure there's at least a handful of gems out there that will handle it for you.

**Comment by amnesia7** [comment]
Thanks that's very helpful. 

I was looking in the direction of a many-to-many setup but it put me off when I found out pg_search couldn't cope with it and that there was no mention of associated-model searching on the Texticle readme.

I've just been looking further into the many-to-many setup for tags and this really is the way I need to go, probably using rocket_tag gem which looks good.

I suppose the only way I'll know for sure is trying out the indexing thing unless anyone can confirm.

**Comment by benhamill** [comment]
Do report back either way, please. :smile:
