### ISSUE TITLE
Search in other languages

### ISSUE THREAD

**Issue by vietqhoang** [texticle/texticle#16]
In my case, I have columns that contain Japanese characters, for example 下がる.

It seems that the gem is set up for english queries only. Is there any possibility in supporting full text search for other languages?

**Comment by benhamill** [comment]
I'm not sure if there are any gotchas with respect to how Postgres handles non-English character sets, but I assume if your table is utf8, you should be good. That being said, you can override the [`searchable_language`](https://github.com/texticle/texticle/blob/master/lib/texticle.rb#L10) method like [this spec](https://github.com/texticle/texticle/blob/master/spec/texticle_spec.rb#L214). You could do it on an individual model like that, or push it up into a parent class, or whatever.

Personally, I'd be open to a pull request improving how this is done or improving the documentation about it. :smile:

**Comment by vietqhoang** [comment]
Yep, the table is in UTF8. Tried doing a search for a non-English string and it returns an empty array, when I was expecting at least one entry.

I'll go ahead and override the method and see how that goes. Will return with results.

**Comment by benhamill** [comment]
Fixed in #17.
