### ISSUE TITLE
Different match modes

### ISSUE THREAD

**Issue by muxamilian** [texticle/texticle#19]
Recently I had the query string `query = "NYC Spam"`. 
In my model the two columns `description` and `location` are being indexed.

So I have a record with `description:  "Spam and eggs", location: "NYC"`

When I run `search(query)` this record is not found. Only when the query is either `"NYC"` or `"Spam"` I get that record back.

So is it currently possible to search like this: To return all results, where each word of the query string is found somewhere in the model?

**Comment by benhamill** [comment]
Off the top of my head, I think the way it works now is that if you feed it just a search string (like you are), it will turn that into the equivalent of `search(description: query, location: query)`. I'm not sure about how Postgres handles this. There may be a query that we could construct that would do it better. If anyone with a deeper understanding can chime in, that'd be great. If not, I'll try to find time to do the research.

**Comment by muxamilian** [comment]
Thank you for your quick reply.

`search(description: query, location: query)` is equivalent to `search_by_description_and_location(query)`. That says that my query string must be contained in `description` and `location`. `search_by_description_or_location(query)` doesn't do what I want either. 

However, I don't think that it is uncommon to search for attributes of a model as I want it. There must be some obvious way to do it...

**Comment by muxamilian** [comment]
You can use `&` and `|` as logical operators in queries ;-)

Would be nice to add this in the documentation.
