### ISSUE TITLE
Fuzzy search condition

### ISSUE THREAD

**Issue by oelmekki** [texticle/texticle#24]
Hello,

If I understand correctly, fuzzy search let search for text containing the given string. But [the where condition](https://github.com/texticle/texticle/blob/master/lib/texticle.rb#L143) is expecting an exact match.

Am I missing something ?

**Comment by oelmekki** [comment]
Nevermind, I didn't understood [the % operator](http://www.postgresql.org/docs/9.1/static/pgtrgm.html).

**Comment by benhamill** [comment]
Cool. Happy you got it sorted. :smile:
