### ISSUE TITLE
How to change the similarity threshold?

### ISSUE THREAD

**Issue by nickw** [texticle/texticle#26]
I'd like to make fuzzy_search be a little more aggressive with the results it returns. For example, currently if I search "Nick" I will get user records with full_name attributes of "Nick Wientge", but not blog records with a title attribute of "Nick Wientge's Cool Blog".

Looking through the postgres docs I noticed a reference to a `set_limit(real)` function that:

> Sets the current similarity threshold that is used by the % operator. The threshold must be between 0 and 1 (default is 0.3). Returns the same value passed in.

http://www.postgresql.org/docs/9.1/static/pgtrgm.html#PGTRGM-FUNC-TABLE

It's not clear to me how I implement this and if it is even compatible with texticle.

**Comment by benhamill** [comment]
Interesting. Do you call it in a query and it's only good for that query or is it something you call and then it's good for the life of your DB connection or what?

Can you suggest an API on the gem's side? If we can come up with a good interface, maybe that'll help us figure out how to think about it as a feature.

**Comment by nickw** [comment]
Apparently you call it in a query: http://stackoverflow.com/a/11250001

I think passing a threshold parameter to fuzzy_search makes sense:

`User.fuzzy_search("Nick", threshold: 0.6)`

Although I could see a use case for setting this globally in a config variable as well.
